name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: practice-runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Se

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image
      - name: Build Docker Image
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice:${{ github.run_id }} -t ${{ secrets.DOCKER_USERNAME}}/practice:latest .

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/practice:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/practice:latest
