name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger action on push to main branch
  pull_request:
    branches:
      - main  # Trigger action on pull request to main branch

jobs:
  build:
    runs-on: practice-runner
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Docker (if not already installed)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build the Docker image
      name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger action on push to main branch
  pull_request:
    branches:
      - main  # Trigger action on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use ubuntu-latest runner (or practice-runner if self-hosted)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ravitejareddybora/practice/simple:${{ github.run_id }}

      # Optional: Remove local Docker images to free up space on the runner
      - name: Cleanup Docker Images
        run: |
          docker rmi -f ravitejareddybora/practice/simple:${{ github.run_id }}
